name: Build and deploy ASP.Net Core app to Azure Web App - hapan9-telegram

on:
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name : build
        uses: ./github/workflows/CI.yml

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hapan9-telegram'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A1E234C5907246869C04A8746B57EA3F }}
          package: .
